<?php
/**
*   File: The Ocean Cleanup Markers
*   Author: https://twitter.com/inevitable360 and all #Dogecoin friends and familly helped will try to find a way to put all names eheh!
*   Description: Real use case of the dogecoin.com CORE Wallet connected by RPC Calls using Old School PHP Coding with easy to learn steps (I hope lol)
*   License: Well, do what you want with this, be creative, you have the wheel, just reenvent and do it better! Do Only Good Everyday
*/
?>
<!-- Here we add The Ocean Cleanup Markers Interceptor to the map -->
<div id="interceptor1" class="interceptor lazyload" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" title="Interceptor - The Ocean Cleanup"></div><script type="text/javascript"> var posinterceptor1 = ol.proj.fromLonLat([106.8695,-6.0081]); var interceptor1 = new ol.Overlay({ position: posinterceptor1, positioning: 'center-center', element: document.getElementById('interceptor1'), stopEvent: false }); map.addOverlay(interceptor1);</script>
<div id="interceptor2" class="interceptor lazyload" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" title="Interceptor - The Ocean Cleanup"></div><script type="text/javascript"> var posinterceptor2 = ol.proj.fromLonLat([101.3475,3.049]); var interceptor2 = new ol.Overlay({ position: posinterceptor2, positioning: 'center-center', element: document.getElementById('interceptor2'), stopEvent: false }); map.addOverlay(interceptor2);</script>
<div id="interceptor3" class="interceptor lazyload" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" title="Interceptor - The Ocean Cleanup"></div><script type="text/javascript"> var posinterceptor3 = ol.proj.fromLonLat([109.204,15.75]); var interceptor3 = new ol.Overlay({ position: posinterceptor3, positioning: 'center-center', element: document.getElementById('interceptor3'), stopEvent: false }); map.addOverlay(interceptor3);</script>
<div id="interceptor4" class="interceptor lazyload" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" title="Interceptor - The Ocean Cleanup"></div><script type="text/javascript"> var posinterceptor4 = ol.proj.fromLonLat([-69.192,19.078]); var interceptor4 = new ol.Overlay({ position: posinterceptor4, positioning: 'center-center', element: document.getElementById('interceptor4'), stopEvent: false }); map.addOverlay(interceptor4);</script>
<div id="interceptor5" class="interceptor lazyload" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" title="Interceptor - The Ocean Cleanup"></div><script type="text/javascript"> var posinterceptor5 = ol.proj.fromLonLat([-77.1062,17.8115]); var interceptor5 = new ol.Overlay({ position: posinterceptor5, positioning: 'center-center', element: document.getElementById('interceptor5'), stopEvent: false }); map.addOverlay(interceptor5);</script>
<div id="interceptor6" class="interceptor lazyload" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" title="Interceptor - The Ocean Cleanup"></div><script type="text/javascript"> var posinterceptor6 = ol.proj.fromLonLat([-118.2156,33.6192]); var interceptor6 = new ol.Overlay({ position: posinterceptor6, positioning: 'center-center', element: document.getElementById('interceptor6'), stopEvent: false }); map.addOverlay(interceptor6);</script>